#!/usr/bin/env node
// Builds the Claude Desktop plugin's server: one self-contained ESM bundle at
// plugins/zendesk-mcp/server/index.js plus the package.json Node needs beside it
// (`"type": "module"`, and the name/version that src/utils/package-info.ts reads
// at runtime). The output is COMMITTED: AEs receive the plugin through the
// Claude organization sync, which ships repository files as they are, with no
// build step and no node_modules on their Macs. Why the bundle is committed,
// why the version is date-based and what CI enforces:
// docs/decisions/plugin-distribution.md.
//
//   pnpm build:plugin          rebuild for the current plugin version
//   pnpm build:plugin --bump   first move the plugin version to today's date
//                              (YYYY.M.D, or YYYY.M.D+N for a same-day
//                              re-release), then rebuild
//
// Deterministic by construction: the same lockfile and sources give the same
// bytes, so .github/workflows/bundle-fresh.yml can rebuild every PR and diff.
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const root = fileURLToPath(new URL('..', import.meta.url));
const pluginDir = join(root, 'plugins', 'zendesk-mcp');
const paths = {
  entry: join(root, 'src', 'index.ts'),
  manifest: join(pluginDir, '.claude-plugin', 'plugin.json'),
  marketplace: join(root, '.claude-plugin', 'marketplace.json'),
  serverDir: join(pluginDir, 'server'),
  bundle: join(pluginDir, 'server', 'index.js'),
  runtimePackage: join(pluginDir, 'server', 'package.json'),
};

/**
 * The bundle keeps the upstream package name on purpose: token-persistence.ts
 * derives the OAuth token directory from it
 * (`~/.config/fruggr/zendesk-mcp-server/<subdomain>.json`), so an AE who signed
 * in through the old manual install keeps that sign-in.
 */
export const RUNTIME_PACKAGE_NAME = '@fruggr/zendesk-mcp-server';

/** Matches package.json#engines.node: the plugin may run on any Node >= 20. */
export const NODE_TARGET = 'node20';

/**
 * Plugin versions are dates, `YYYY.M.D` with no zero padding, plus `+N` for the
 * Nth re-release of the same day. Three numeric segments keep the string
 * semver-shaped, which Claude's plugin tooling expects and which the
 * claude-org-management linter enforces on the vendored copy; the `+N` build
 * metadata is the same convention Measurabl's chad-gpt plugin already ships.
 */
export const PLUGIN_VERSION_PATTERN =
  /^20\d{2}\.(?:[1-9]|1[0-2])\.(?:[1-9]|[12]\d|3[01])(?:\+[1-9]\d*)?$/;

export const todayVersion = (date = new Date()) =>
  `${date.getUTCFullYear()}.${date.getUTCMonth() + 1}.${date.getUTCDate()}`;

/** Today's version, or `+N` when `current` already carries today's date. */
export const nextVersion = (current, date = new Date()) => {
  const today = todayVersion(date);
  const [base, suffix] = current.split('+');
  if (base !== today) return today;
  return `${today}+${suffix === undefined ? 1 : Number(suffix) + 1}`;
};

/** The package.json written beside the bundle; tests assert the committed copy equals this. */
export const runtimePackageJson = (version) => ({
  name: RUNTIME_PACKAGE_NAME,
  version,
  private: true,
  type: 'module',
  description:
    'Bundled Zendesk MCP server for the zendesk-mcp Claude plugin. Generated by scripts/build-plugin.mjs; do not edit by hand.',
});

// esbuild's ESM output leaves the CommonJS `require` to the host, and Node has
// none in an ES module: without this shim every bundled CommonJS dependency
// that `require`s a Node built-in throws "Dynamic require of ... is not
// supported" at startup.
const BANNER = [
  "import { createRequire as __zmcpCreateRequire } from 'node:module';",
  'const require = __zmcpCreateRequire(import.meta.url);',
].join('\n');

const readManifestVersion = () => {
  const manifest = JSON.parse(readFileSync(paths.manifest, 'utf8'));
  if (typeof manifest.version !== 'string' || !PLUGIN_VERSION_PATTERN.test(manifest.version)) {
    throw new Error(
      `${relative(root, paths.manifest)}: version ${JSON.stringify(manifest.version)} is not YYYY.M.D[+N]`,
    );
  }
  return manifest.version;
};

// A targeted text replacement rather than JSON.parse/stringify, so the two
// manifests keep the formatting Biome gives them (single-line arrays etc.).
const replaceVersion = (path, from, to) => {
  const text = readFileSync(path, 'utf8');
  const needle = `"version": "${from}"`;
  const occurrences = text.split(needle).length - 1;
  if (occurrences !== 1) {
    throw new Error(
      `${relative(root, path)}: expected exactly one ${needle}, found ${occurrences}`,
    );
  }
  writeFileSync(path, text.replace(needle, `"version": "${to}"`));
};

const bump = () => {
  const from = readManifestVersion();
  const to = nextVersion(from);
  replaceVersion(paths.manifest, from, to);
  replaceVersion(paths.marketplace, from, to);
  console.error(`[build-plugin] plugin version ${from} -> ${to}`);
  return to;
};

const bundle = async (version) => {
  // Regenerate from scratch so nothing stale can survive in the shipped directory.
  rmSync(paths.serverDir, { recursive: true, force: true });
  mkdirSync(paths.serverDir, { recursive: true });
  await build({
    absWorkingDir: root,
    entryPoints: [paths.entry],
    outfile: paths.bundle,
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: NODE_TARGET,
    banner: { js: BANNER },
    // Readable output: the bundle is reviewed in PRs and debugged from AE Macs.
    minify: false,
    sourcemap: false,
    legalComments: 'none',
    logLevel: 'warning',
  });
  writeFileSync(paths.runtimePackage, `${JSON.stringify(runtimePackageJson(version), null, 2)}\n`);
  const bytes = statSync(paths.bundle).size;
  const sha256 = createHash('sha256').update(readFileSync(paths.bundle)).digest('hex');
  console.error(
    `[build-plugin] ${relative(root, paths.bundle)}: ${(bytes / 1024 / 1024).toFixed(2)} MB, sha256 ${sha256}`,
  );
  console.error(`[build-plugin] ${relative(root, paths.runtimePackage)}: version ${version}`);
};

// Only act when run directly, not when imported by a test.
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2);
  const unknown = args.filter((arg) => arg !== '--bump');
  if (unknown.length > 0) {
    console.error(
      `[build-plugin] unknown argument(s): ${unknown.join(' ')} (only --bump is accepted)`,
    );
    process.exit(2);
  }
  const version = args.includes('--bump') ? bump() : readManifestVersion();
  await bundle(version);
}
